In [1]:
!pip install sktime

     |████████████████████████████████| 5.8 MB 14.3 MB/s 
     |████████████████████████████████| 22.3 MB 35 kB/s 
     |████████████████████████████████| 9.5 MB 42.5 MB/s 
  Attempting uninstall: statsmodels
    Found existing installation: statsmodels 0.10.2
    Uninstalling statsmodels-0.10.2:
      Successfully uninstalled statsmodels-0.10.2
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 0.22.2.post1
    Uninstalling scikit-learn-0.22.2.post1:
      Successfully uninstalled scikit-learn-0.22.2.post1


In [2]:
import os
import sys
import time
import math
import numpy as np
from sklearn import tree
from sklearn import metrics
from sklearn.metrics import f1_score
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler
import csv
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

import shutil
import errno
import time
import fnmatch
from sklearn.neural_network import MLPClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import ComplementNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import CategoricalNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

from sktime.classification.interval_based import TimeSeriesForestClassifier



In [5]:
from google.colab import files
uploaded = files.upload()

Saving combined_ben-mal-bal.csv to combined_ben-mal-bal.csv
Saving combined_ben-mal-timeseries.csv to combined_ben-mal-timeseries (1).csv
Saving combined_ben-mal-unb.csv to combined_ben-mal-unb.csv


In [57]:
# Regular Traditional HPC-based Classification------------------------------------Start Here-------------------------------


kyber1 = pd.read_csv('combined_ben-mal-unb.csv')       

frames = [kyber1]
mergedset = pd.concat(frames)

x = mergedset.iloc[:, [1,3,23]].values
y = mergedset.iloc[:, 30].values


#print(len(x))
#print(len(y))
#print(x)
#print(y)


X_train,X_test, Y_train, Y_test = train_test_split(x,y, test_size= 0.20, shuffle=True)


scaler = StandardScaler()  
scaler.fit(X_train)

X_train = scaler.transform(X_train)  
X_test = scaler.transform(X_test)  


#clf = tree.DecisionTreeClassifier(max_depth=10)
clf = MLPClassifier(hidden_layer_sizes=(10,10),max_iter=200)
#clf = RandomForestClassifier(n_estimators = 30,max_depth=5)
clf.fit(X_train,Y_train)

y_pred = clf.predict(X_test)
print("Number of Samples", len(X_test))
print("Accuracy: ", np.mean(y_pred==Y_test))
precision1 = precision_score(y_pred, Y_test)
print('Precision: %f' % precision1)
recall1 = recall_score(y_pred, Y_test)
print('Recall: %f' % recall1)

for i in range(0, len(y_pred)):
  if Y_test[i] == 0: 
    print(Y_test[i] , '  ', y_pred[i])



Number of Samples 58
Accuracy:  0.8448275862068966
Precision: 1.000000
Recall: 0.844828
0    1
0    1
0    1
0    1
0    1
0    1
0    1
0    1
0    1


In [26]:
# Regular Traditional HPC-based Classification------------------------------------Start Here-------------------------------


kyber1 = pd.read_csv('combined_ben-mal-bal.csv')       

frames = [kyber1]
mergedset = pd.concat(frames)

x = mergedset.iloc[:, [1,3,23]].values
y = mergedset.iloc[:, 30].values


print(len(x))
print(len(y))
print(x)
print(y)


X_train,X_test, Y_train, Y_test = train_test_split(x,y, test_size= 0.20, shuffle=True)


scaler = StandardScaler()  
scaler.fit(X_train)

X_train = scaler.transform(X_train)  
X_test = scaler.transform(X_test)  



clf = RandomForestClassifier(n_estimators = 50,max_depth=6)
#clf = GaussianNB(var_smoothing=10000)
#clf = MultinomialNB()
#clf = ComplementNB()
#clf = BernoulliNB()
#clf = CategoricalNB()
#clf = KNeighborsClassifier(n_neighbors=4)
#clf = LogisticRegression(solver='saga')
#clf = LogisticRegression(max_iter=10000)
#clf = RandomForestClassifier(max_features=4)
#clf = RandomForestClassifier(max_depth=1000)
#clf = SVC(C=2)
#clf = MLPClassifier(hidden_layer_sizes=(10,10),max_iter=200)



clf.fit(X_train,Y_train)

y_pred = clf.predict(X_test)
print("Number of Samples", len(X_test))
print("Accuracy: ", np.mean(y_pred==Y_test))
precision1 = precision_score(y_pred, Y_test)
print('Precision: %f' % precision1)
recall1 = recall_score(y_pred, Y_test)
print('Recall: %f' % recall1)

for i in range(0, len(y_pred)):
  if Y_test[i] == 0: 
    print(Y_test[i] , '  ', y_pred[i])


451
451
[[ 4 10  1]
 [ 0 31  0]
 [ 0 26  0]
 ...
 [ 2  8  1]
 [ 1 15  0]
 [12 19  3]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1

In [ ]:
#################-----------------Multiple HPCs New Code --------------------------------------------------------------------------------

#change length of dataset, samplesperprogram, and the different time variations you want, program does rest!
filename = 'combined_ben-mal-timeseries.csv'                      # change file name
lengthofdataset = 440 			 	# length of the dataset (num samples)
samplesperprogram = 55					# how many samples per program
timeserieslength = 5					# Time series length you want
locofclasslabel = 30					# location of the class label (benign and malware) 
column_vals = [0]					   # which HPCs that should be utilized 


numsamples = samplesperprogram - (samplesperprogram % timeserieslength)
kyber1 = pd.read_csv(filename)       
frames = [kyber1]
mergedset = pd.concat(frames)
X = mergedset.iloc[:, column_vals].values
y = mergedset.iloc[:, locofclasslabel].values

X = np.reshape(X, (lengthofdataset*len(column_vals),1),order='F')
y = np.repeat(y, len(column_vals), axis = 0)


vpsplit_val = (((lengthofdataset/samplesperprogram) * math.floor(samplesperprogram/timeserieslength)) * len(column_vals))
temp = []
temp1 = []
temp2 = []
counter = 0
totalsamples = 0
val = 0

print(len(X))

#create individual time series arrays
while val < len(X):
	if counter < timeserieslength:
		temp1 = np.append(temp1,X[val])
		if counter == 0:
			temp2.append(y[val])
		counter +=1
		totalsamples += 1
		
	if counter == timeserieslength:
		counter = 0
		temp.append(temp1)
		temp1 = []

	if totalsamples == numsamples:
		val += samplesperprogram % timeserieslength
		totalsamples = 0
	val = val + 1


X = temp
y = temp2
X = np.array(X)
y = np.array(y)

X = np.vsplit(X,vpsplit_val)             
X = np.array(X)


print(len(X))

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)



#this classifier works
tsf = TimeSeriesForestClassifier(n_estimators=10,min_interval=2)

tsf.fit(X_train, y_train)

y_pred = tsf.predict(X_test)
print("Number of testing samples", len(X_test))



print("Accuracy for time series length: ", timeserieslength , " HPC columns: " , column_vals,  ": ", np.mean(y_pred==y_test))
precision1 = precision_score(y_pred, y_test)
print('Precision: %f' % precision1)
recall1 = recall_score(y_pred, y_test)
print('Recall: %f' % recall1)

tp = 0
fp = 0
tn = 0
fn = 0
for i in range(0,len(y_test)):
  if y_test[i] == 0 and y_pred[i] == 0:
    tn += 1
  if y_test[i] == 1 and y_pred[i] == 1:
    tp += 1
  if y_test[i] == 0 and y_pred[i] == 1:
      fp += 1
  if y_test[i] == 1 and y_pred[i] == 0:
      fn += 1

print(tp)
print(fp)
print(tn)
print(fn)
print(tp/(tp + fp))
print(tp/(tp+fn))
for i in range(0,len(y_test)):
  if y_test[i] == 0 and y_pred[i] == 1:
    print('wrong good')
  if y_test[i] == 1 and y_pred[i] == 0:
    print('wrong bad')
#print(X_test)
print(y_pred)
print(y_test)

440
88
Number of testing samples 18
Accuracy for time series length:  5  HPC columns:  [0] :  0.6111111111111112
Precision: 0.300000
Recall: 1.000000
3
0
8
7
1.0
0.3
wrong bad
wrong bad
wrong bad
wrong bad
wrong bad
wrong bad
wrong bad
[0 0 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0]
[1 0 0 1 0 1 1 1 1 0 1 0 1 1 1 0 0 0]


In [12]:

# Feature Extraction with PCA
import numpy
from pandas import read_csv
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
# load data
names = ['numa','numb','nums','numl','numx','numbx','numbb','numbl','numbs','numba','numlx','numll','numlb','numls','numla','numsx', 'numss','numsb','numsl','numsa','numax','numaa','numab','numal','numas','numxx','numxb','numxs','numxl','numxa','class']
filename = 'combined_ben-mal-timeseries.csv'
filename = 'combined_ben-mal-bal.csv'
filename = 'combined_ben-mal-unb.csv'
dataframe = pd.read_csv(filename)       


print(dataframe)
array = dataframe.values
print(array)
X = array[:,0:30]
print('----------------------------------------------------------------------')
print(X)
X = StandardScaler().fit_transform(X)
print(X)
Y = array[:,30]
print(Y)
# feature extraction
pca = PCA(n_components=4)
fit = pca.fit(X)
# summarize components
print("Explained Variance: %s" % fit.explained_variance_ratio_)
print(fit.components_)

for i in range(0,len(fit.components_)):
	ans = fit.components_[i][0]
	pos = 0
	for j in range(0,len(fit.components_[i])):
		if ans < fit.components_[i][j]:
			ans = fit.components_[i][j]
			pos = j
	print(ans, " ",  pos+1," ", names[pos])

     5  6  12  18   1  0  0.1  2  ...  3  0.8  0.9  0.10  0.11  0.12  0.13  1.5
0    8  4  13  10   3  0    1  2  ...  1    4    0     0     3     0     0    1
1    2  0   1  31  10  0    0  0  ...  0    1    0    10     0    10     0    1
2    2  0   5  26  10  0    0  0  ...  0    1    0     9     0     9     0    1
3    7  3   8  16   9  0    0  3  ...  0    6    5     1     0     1     0    1
4    0  7   1  17  21  0    0  7  ...  0    0   12     2     0     2     0    1
..  .. ..  ..  ..  .. ..  ... ..  ... ..  ...  ...   ...   ...   ...   ...  ...
281  1  8   7  16   9  1    1  3  ...  0    0    1     4     1     4     0    0
282  1  4   8  12  14  0    0  1  ...  0    1    7     1     3     1     0    0
283  2  2  10  12   9  0    0  0  ...  0    1    5     1     2     1     0    0
284  0  9  20  17   1  0    2  7  ...  0    0    0     0     1     0     0    0
285  6  6   9  19   1  0    0  5  ...  4    0    0     0     1     0     0    0

[286 rows x 31 columns]
[[ 8  4 13 ... 